| Technique | Type | Incident Source | Target Objects | Range/Depth | Principle | Detected Signal | Key Components | Core Formula/Theory | Key Indicators |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| **XRD** | Non-destructive | X-rays | Crystalline, Polycrystalline, Amorphous | Bulk/Atomic structure | Elastic scattering & interference | Diffracted X-rays | X-ray source, Goniometer, Detector | $n\lambda = 2d\sin\theta$ (Bragg's Law) | Peak position ($2\theta$), Intensity, FWHM |
| **XRF** | Non-destructive | X-rays | Materials for elemental analysis | Surface/Thin layers | Emission of characteristic X-rays | Fluorescent X-rays | X-ray tube, Detector (ED or WD) | Moseley's Law | Peak energy (element ID), Intensity (conc.) |
| **FTIR** | Non-destructive | Infrared (IR) light | Molecules, Polymers | Molecular bonds | Absorption of IR radiation by vibrating bonds | Transmitted/Absorbed IR light | IR Source, Interferometer, Detector | Selection Rule: Change in dipole moment | Peak position (wavenumber), Intensity |
| **Raman** | Non-destructive | Laser (Visible/NIR) | Molecules, Semiconductors | Molecular vibrations | Inelastic scattering of photons | Scattered photons (Stokes/Anti-Stokes) | Laser, Lenses, Spectrometer, CCD | Selection Rule: Change in polarizability | Raman Shift ($\Delta w$), Peak intensity |
| **OM** | Non-destructive | Visible light | Cells, Ceramics, Metals | Micro-scale surface | Reflection/Refraction of visible light | Visible light | Objective lens, Eyepiece, Light source | $R = \frac{0.61\lambda}{NA}$ (Resolution) | Image contrast, Resolution |
| **SEM** | Non-destructive (generally) | Electron beam | Nanomaterials, Devices, Polymers | Surface (nm to $\mu m$) | Scanning electron-matter interaction | SE, BSE, Auger e-, X-rays | Electron gun, EM lenses, Detectors | de Broglie wavelength | Morphology, Topography, Composition |
| **TEM** | Destructive (sample prep) | Electron beam | Thin foils, Nanoparticles | Bulk structure (atomic scale) | Transmission & diffraction of electrons | Transmitted e-, Diffracted e- | Electron gun, EM lenses, CCD | $R = \frac{0.61\lambda}{\mu \sin\alpha}$ | Lattice fringes, Diffraction spots |
| **XPS** | Non-destructive | X-rays | Solids, Surfaces | Surface ($<10$ nm) | Photoelectric effect | Photoelectrons | X-ray source, Analyzer, Detector | $E_b = hv - E_k - \phi$ | Binding energy shift, Spin-orbit splitting |
| **SIMS** | Destructive | Ion beam (Primary) | Insulators, Semiconductors | Surface (0.1-1 nm) to Depth profiling | Sputtering of surface atoms | Secondary Ions | Ion gun, Mass analyzer, Detector | Mass-to-charge ratio ($m/z$) | Secondary ion yield, Depth profile |
| **UV-Vis** | Non-destructive | UV & Visible light | Liquids, Thin films, Glass | Electronic transitions | Absorption of light by valence electrons | Transmitted light | Light source, Monochromator, Detector | $A = \epsilon bc$ (Beer-Lambert Law) | Absorbance, Band gap edge |
| **PL** | Non-destructive | Light (Photons) | Semiconductors | Electronic structure | Emission of light during relaxation | Photons (Fluorescence/Phospho.) | Excitation source, Monochromator | Electronic transition energy | Peak energy, Intensity, Lifetime |